In [1]:
import pandas as pd
from glob import glob
import os

In [2]:
df = pd.read_csv(r'~/Desktop/covid/COVID_Cases_Restricted_Detailed_05172020.csv')       
df.head()

,current_status,cdc_report_dt,sex,age_group,race_combined,ethnicity,onset_dt,pos_spec_dt,hosp_yn,icu_yn,...,myalgia_yn,runnose_yn,sthroat_yn,cough_yn,sob_yn,nauseavomit_yn,headache_yn,abdom_yn,diarrhea_yn,medcond_yn
0,Laboratory-confirmed case,2020-03-28,Female,20 - 29 Years,American Indian/Alaska Native,Hispanic/Latino,NaN,2020-03-22,No,No,...,Unknown,Unknown,Unknown,Unknown,Yes,Unknown,Unknown,Unknown,Unknown,Yes
1,Laboratory-confirmed case,2020-04-08,Female,20 - 29 Years,American Indian/Alaska Native,Hispanic/Latino,NaN,2020-04-02,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Yes
2,Laboratory-confirmed case,2020-04-01,Female,20 - 29 Years,American Indian/Alaska Native,Hispanic/Latino,2020-03-27,NaN,No,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,Laboratory-confirmed case,2020-04-03,Female,20 - 29 Years,American Indian/Alaska Native,Hispanic/Latino,2020-03-18,2020-03-22,Yes,No,...,Yes,Yes,No,Yes,No,Yes,Yes,Yes,Yes,Yes
4,Laboratory-confirmed case,2020-04-08,Female,20 - 29 Years,American Indian/Alaska Native,Hispanic/Latino,2020-03-19,2020-03-24,No,Unknown,...,Yes,Unknown,Unknown,Yes,No,No,Yes,No,No,No

In [3]:
filepath = os.path.expanduser(r'~/Desktop/covid')
os.chdir(filepath)
files = glob('*.csv')
files

['COVID_Cases_Restricted_Detailed_07312020.csv',
 'COVID_Cases_Restricted_Detailed_09302020.csv',
 'COVID_Cases_Restricted_Detailed_06272020.csv',
 'COVID_Cases_Restricted_Detailed_05292020.csv',
 'COVID_Cases_Restricted_Detailed_05172020.csv',
 'COVID_Cases_Restricted_Detailed_08312020.csv']

In [4]:
files.sort()
files

['COVID_Cases_Restricted_Detailed_05172020.csv',
 'COVID_Cases_Restricted_Detailed_05292020.csv',
 'COVID_Cases_Restricted_Detailed_06272020.csv',
 'COVID_Cases_Restricted_Detailed_07312020.csv',
 'COVID_Cases_Restricted_Detailed_08312020.csv',
 'COVID_Cases_Restricted_Detailed_09302020.csv']

In [5]:
data = pd.concat(pd.read_csv(file) for file in files)
data.tail()

,current_status,cdc_report_dt,sex,age_group,race_combined,ethnicity,onset_dt,pos_spec_dt,hosp_yn,icu_yn,...,sob_yn,nauseavomit_yn,headache_yn,abdom_yn,diarrhea_yn,medcond_yn,race_ethnicity_combined,county_fips_code,res_county,res_state
4481057,Laboratory-confirmed case,2020-04-14,Female,60 - 69 Years,NaN,NaN,2020-03-29,2020-03-30,No,No,...,No,No,No,No,No,Yes,Hispanic/Latino,42133,York,PA
4481058,Laboratory-confirmed case,2020-08-10,Female,60 - 69 Years,NaN,NaN,2020-07-21,2020-08-08,Yes,No,...,Yes,No,Yes,No,Yes,Yes,Hispanic/Latino,42133,York,PA
4481059,Laboratory-confirmed case,2020-08-10,Female,60 - 69 Years,NaN,NaN,2020-07-15,2020-08-03,No,No,...,No,Yes,Yes,No,Yes,Yes,Hispanic/Latino,42133,York,PA
4481060,Laboratory-confirmed case,2020-08-27,Female,60 - 69 Years,NaN,NaN,2020-08-10,2020-08-20,No,No,...,No,No,Yes,No,No,Yes,Hispanic/Latino,42133,York,PA
4481061,Laboratory-confirmed case,2020-05-23,Female,60 - 69 Years,NaN,NaN,2020-05-10,2020-05-14,No,No,...,No,No,Yes,No,No,Yes,Hispanic/Latino,42133,York,PA